algoritmo "Idade"
// Função :LOPAL (Lógica de programação)
// Autor : Caline Myrella
// Data : 13/04/2026
// Seção de Declarações 
var
//Declaração de variaveis

idade: real

inicio
// Seção de Comandos 

   escreva ("Digite sua idade")
   leia (idade)
   
   se idade>=18 entao
   
   escreval ("maior de idade, pode dirigir")
   
   senao
   
   escreval ("menor de idade pode ")
    fimse

fimalgoritmo
