algoritmo "Idade"
// Função :LOPAL (Lógica de programação)

// Autor : Caline Myrella
// Data : 13/04/2026
// Seção de Declarações 
var
//Declaração de variaveis

senha:literal

inicio
// Seção de Comandos 

   escreva ("digite a senha")
   leia (senha)
   
   se senha="acb23" entao
   
   escreval ("senha correta ")
   
   senao
   
   escreval ("senha incorreta ")
    fimse

fimalgoritmo
