algoritmo "soma dos numeros"

// Autor : Caline Myrella
// Data : 13/04/2026
// Seção de Declarações 
var
 //Declaração de variáveis
 numero1, numero2, numero3, soma: real
inicio
 //Seção de comandos
 
      escreva ("informe o numero1: ")
      leia(numero1)
      
      escreva ("informe o numero2: ")
      leia(numero2)
      
      escreva ("informe o numero3: ")
      leia(numero3)
      
 //realizar a soma dos três numeros
      
      soma<- numero1 + numero2 + numero3
      
      escreval ("valor da soma dos numeros", soma)
      

fimalgoritmo
