algoritmo "Soma dos números"
// Função : LOPAL (Lógica de Programação)

//F9 (executava meu código)

// Autor :  Caline Myrella
// Data : 13/04/2026
var
 //Declaração de variáveis
 
 base,altura,largura,volume,valorFinal: real
inicio
// Inicio dos dados

   escreva ("coloque o primeiro valor: ")
   leia (base)
   
   escreva ("coloque o segundo valor: ")
   leia(altura)
   
   escreva ("coloque o terceiro valor: ")
   leia (largura)
 
 //realizar a divisão e a multiplicação do peso e alturas
 valorFinal<- base * altura * largura
 
 escreval ("o valorFinal do voume", valorFinal)


fimalgoritmo
